### ISSUE TITLE
Some project folders are not created

### ISSUE THREAD

**Issue by sdhutchins** [kalekundert/exmemo#1]
Hey, I really dig this package! It's extremely well written.

I'm curious if this has been tested on windows?

When I try the `exmemo note new "Large step with half twist"`, it just hangs. Also, when I create a new project, the `documents`, `data`, and `protocols` folders aren't created.  I'm not sure if this is a bug or not.

@kalekundert

**Comment by kalekundert** [comment]
Thanks for the bug report!  I have not tested it on Windows, so that could be part of the problem.  My guess is that the ``exmemo note new`` command is hanging because it's having trouble lauching your text editor.   If that's the case, you might be able to fix the problem by either setting ``editor = ...`` in one of the config files (see ``exmemo config -h`` for the correct paths and file format), or setting the $EDITOR environment variable.  If that's not the case, could you ``Ctrl-C`` the command while it's hanging and show me the stack trace that results?  And really, either way, I'd like to get it so it never hangs by default.

The failure to create the ``documents``, ``data``, and ``protocols`` directories is definitely a bug.  I just pushed a commit that I think should fix it, so let me know if it works for you now.

**Comment by sdhutchins** [comment]
Awesome! Thanks for the prompt response. I'm going to test it on my work desktop in the morning and let you know how it goes.

**Comment by sdhutchins** [comment]
Hey, I just tested it out @kalekundert, and it's working although throwing a Windows path error while still creating a file. I just pushed a fix to my fork of this project, and I'll try to make a PR at some point this week if that's cool. Again, I love this project. I did a lot of looking at different projects like this one in R, python, and html and so far, this one is exactly what I've been wanting. I'm excited to also add some portable features to this to fit some of my own needs.

**Comment by kalekundert** [comment]
Definitely make a PR.  And I'm glad you like the framework; hopefully you can get it to fit your needs without too much hassle.  Let me know if you have any problems, and I'd be happy to get PRs for any generally useful features you add!

**Comment by kalekundert** [comment]
Fixed by #2
